---
site_name: "Syndio Backend Test"
site_description: "Demo an API with data read from a sqlite."
site_url: ""
repo_url: "https://github.com/xsc27/syndio_backend_test"
repo_name: "xsc27/syndio_backend_test"
remote_branch: "gh-pages"
theme:
  name: "material"
  palette:
    scheme: slate
use_directory_urls: false

markdown_extensions:
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- toc:
    permalink: true

plugins:
- exclude:
    glob:
    - "_scripts/**"
- search
- section-index
- gen-files:
    scripts:
    - docs/_scripts/gen_stubs.py
- mkdocstrings:
    handlers:
      python:
        rendering:
          show_if_no_docstring: true
          show_signature_annotations: true
    watch:
    - src
