---
name: CI

on: [ push ]

jobs:

  pre-commit:
    name: Pre-Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.3

  tox:
    name: ${{ matrix.env }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [ lint, py ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install tox
      - run: tox -e ${{ matrix.env }}

  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python3 -m pip install --user tox
      - run: tox -e docs -- gh-deploy --force
